# Site settings
title:       Dungeon Advisor
email:       royletron@gmail.com
author:      Royletron
description: "The only place for your Dungeon Advisor development news."
baseurl:     "http://royletron.github.io/dungeon-advisor/"
url:         "http://royletron.github.io/dungeon-advisor/"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: royletron
bitbucket_username:
stackoverflow_id:
twitter_username: royletron
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: false
share_stumbleupon: false
share_hackernews: false

gems:
  - jemoji

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
